#!/usr/bin/env bash
set -euo pipefail
git add -- \
  '.eslintrc.json' \
  'backend-src/app.ts' \
  'backend-src/controllers/financial.controller.ts' \
  'backend-src/controllers/invoices.controller.ts' \
  'backend-src/controllers/payables.controller.ts' \
  'backend-src/controllers/purchases.controller.ts' \
  'backend-src/controllers/quotes.controller.ts' \
  'backend-src/controllers/receivables.controller.spec.ts' \
  'backend-src/controllers/receivables.controller.ts' \
  'backend-src/controllers/reconciliation.controller.ts' \
  'backend-src/controllers/reports.controller.ts' \
  'backend-src/controllers/settings.controller.ts' \
  'backend-src/controllers/suppliers.controller.ts' \
  'backend-src/controllers/webhook.controller.ts' \
  'backend-src/core/middlewares/tenantGuard.spec.ts' \
  'backend-src/core/middlewares/tenantGuard.ts' \
  'backend-src/integrations/core/external-order-ingestion.service.ts' \
  'backend-src/integrations/ifood/ifood-catalog.service.ts' \
  'backend-src/integrations/ifood/ifood-merchant.service.ts' \
  'backend-src/middlewares/requireAdmin.ts' \
  'backend-src/middlewares/requireRole.ts' \
  'backend-src/routes/admin.routes.ts' \
  'backend-src/routes/api-smoke.spec.ts' \
  'backend-src/routes/billing.routes.ts' \
  'backend-src/routes/customer.routes.ts' \
  'backend-src/routes/delivery.routes.ts' \
  'backend-src/routes/financial.routes.ts' \
  'backend-src/routes/fiscal.routes.ts' \
  'backend-src/routes/health.routes.ts' \
  'backend-src/routes/inventory.routes.ts' \
  'backend-src/routes/kds.routes.spec.ts' \
  'backend-src/routes/kds.routes.ts' \
  'backend-src/routes/manufacturing.routes.ts' \
  'backend-src/routes/order-checkout.spec.ts' \
  'backend-src/routes/order.routes.ts' \
  'backend-src/routes/payables.routes.ts' \
  'backend-src/routes/pos.routes.spec.ts' \
  'backend-src/routes/pos.routes.ts' \
  'backend-src/routes/product.routes.ts' \
  'backend-src/routes/purchases.routes.ts' \
  'backend-src/routes/receivables.routes.ts' \
  'backend-src/routes/recipe.routes.ts' \
  'backend-src/routes/reports.routes.spec.ts' \
  'backend-src/routes/saas.routes.ts' \
  'backend-src/routes/tenant.routes.ts' \
  'backend-src/routes/waste.routes.ts' \
  'backend-src/seed.ts' \
  'backend-src/services/FiscalService.ts' \
  'backend-src/services/PaymentGatewayService.spec.ts' \
  'backend-src/services/PaymentGatewayService.ts' \
  'backend-src/services/crm.service.ts' \
  'backend-src/services/financialAnalytics.service.spec.ts' \
  'backend-src/services/financialAnalytics.service.ts' \
  'backend-src/services/manufacturing.service.spec.ts' \
  'backend-src/services/manufacturing.service.ts' \
  'backend-src/services/orderEvents.service.spec.ts' \
  'backend-src/services/orderEvents.service.ts' \
  'backend-src/services/orderFinancial.service.ts' \
  'backend-src/services/payables.service.spec.ts' \
  'backend-src/services/payables.service.ts' \
  'backend-src/services/purchasing.service.ts' \
  'backend-src/services/shiftAudit.service.spec.ts' \
  'backend-src/services/shiftAudit.service.ts' \
  'backend-src/services/storeSettings.service.ts' \
  'backend-src/services/tenantSettingsFs.service.ts' \
  'backend-src/services/waste.service.ts' \
  'backend-src/utils/adminRoles.spec.ts' \
  'backend-src/utils/adminRoles.ts' \
  'backend-src/utils/csvSanitizer.spec.ts' \
  'backend-src/utils/csvSanitizer.ts' \
  'backend-src/utils/kdsHelpers.spec.ts' \
  'backend-src/utils/kdsHelpers.ts' \
  'backend-src/utils/normalize.ts' \
  'backend-src/utils/timezone.spec.ts' \
  'backend-src/utils/timezone.ts' \
  'fix_admin_owner.js' \
  'frontend-src/components/AuthModal.jsx' \
  'frontend-src/components/Button.jsx' \
  'frontend-src/components/ERPLayout.jsx' \
  'frontend-src/components/ErrorBoundary.jsx' \
  'frontend-src/components/LoyaltyWidget.jsx' \
  'frontend-src/components/ProductCustomizationModal.jsx' \
  'frontend-src/components/admin/AdminUI.jsx' \
  'frontend-src/components/admin/CategoryModal.jsx' \
  'frontend-src/components/admin/CouponModal.jsx' \
  'frontend-src/components/admin/POSQuickPayModal.jsx' \
  'frontend-src/components/admin/POSReceiptModal.jsx' \
  'frontend-src/components/admin/PrintReceipt.jsx' \
  'frontend-src/components/admin/ProductModal.jsx' \
  'frontend-src/components/admin/ShiftModals.jsx' \
  'frontend-src/components/public/FloatingWhatsApp.jsx' \
  'frontend-src/components/public/PublicFooter.jsx' \
  'frontend-src/components/ui/BaseModal.jsx' \
  'frontend-src/components/ui/BottomNav.jsx' \
  'frontend-src/components/ui/CartDrawer.jsx' \
  'frontend-src/components/ui/FloatingCartButton.jsx' \
  'frontend-src/components/ui/PageContainer.jsx' \
  'frontend-src/components/ui/ProductSkeleton.jsx' \
  'frontend-src/components/ui/StoreClosedModal.jsx' \
  'frontend-src/components/ui/ToastProvider.jsx' \
  'frontend-src/data/menuData.js' \
  'frontend-src/main.jsx' \
  'frontend-src/pages/AccountPage.jsx' \
  'frontend-src/pages/CheckoutPage.jsx' \
  'frontend-src/pages/HomePage.jsx' \
  'frontend-src/pages/KDS/KitchenDisplay.jsx' \
  'frontend-src/pages/MockPaymentPage.jsx' \
  'frontend-src/pages/OrderStatusPage.jsx' \
  'frontend-src/pages/POS/POSScreen.jsx' \
  'frontend-src/pages/admin/AccountsPayable.jsx' \
  'frontend-src/pages/admin/AccountsReceivable.jsx' \
  'frontend-src/pages/admin/AdminLayout.jsx' \
  'frontend-src/pages/admin/AdminsPage.jsx' \
  'frontend-src/pages/admin/CRMPage.jsx' \
  'frontend-src/pages/admin/CashFlowPage.jsx' \
  'frontend-src/pages/admin/CategoriesPage.jsx' \
  'frontend-src/pages/admin/CouponsPage.jsx' \
  'frontend-src/pages/admin/DREPage.jsx' \
  'frontend-src/pages/admin/DashboardPage.jsx' \
  'frontend-src/pages/admin/DeliverySettings.jsx' \
  'frontend-src/pages/admin/DispatchPage.jsx' \
  'frontend-src/pages/admin/EditInvoiceModal.jsx' \
  'frontend-src/pages/admin/FiscalPage.jsx' \
  'frontend-src/pages/admin/InventoryPage.jsx' \
  'frontend-src/pages/admin/InvoicesPage.jsx' \
  'frontend-src/pages/admin/KDSPage.jsx' \
  'frontend-src/pages/admin/NewPayableModal.jsx' \
  'frontend-src/pages/admin/NewQuoteModal.jsx' \
  'frontend-src/pages/admin/OptionsPage.jsx' \
  'frontend-src/pages/admin/OrdersPage.jsx' \
  'frontend-src/pages/admin/POSPage.jsx' \
  'frontend-src/pages/admin/PayablePaymentModal.jsx' \
  'frontend-src/pages/admin/ProductsPage.jsx' \
  'frontend-src/pages/admin/PurchasesPage.jsx' \
  'frontend-src/pages/admin/Quotes.jsx' \
  'frontend-src/pages/admin/RecipesPage.jsx' \
  'frontend-src/pages/admin/ReconciliationPage.jsx' \
  'frontend-src/pages/admin/RecordPaymentModal.jsx' \
  'frontend-src/pages/admin/ReportsPage.jsx' \
  'frontend-src/pages/admin/ReversePaymentModal.jsx' \
  'frontend-src/pages/admin/SettingsPage.jsx' \
  'frontend-src/pages/admin/ShiftAuditPage.jsx' \
  'frontend-src/pages/admin/SuppliersPage.jsx' \
  'frontend-src/pages/saas/OnboardingPage.jsx' \
  'frontend-src/pages/saas/SaasDashboardPage.jsx' \
  'frontend-src/store/useCartStore.js' \
  'frontend-src/styles.css' \
  'frontend-src/utils/csvHelper.js' \
  'index.html' \
  'scripts/migrate-categories.mjs' \
  'scripts/seed_professional_menu.ts' \
  'update-admin.ts'
